config/routes.rb
Rails.application.routes.draw do
  resources :words do
    collection do
      get 'get_path'
      get 'get_random_path'
    end
  end

end

app/models/word.rb
class Word 
  include Neo4j::ActiveNode
  property :name, type: String

  def self.find_path(source, target)
    source_word =  Word.find_by(name: source).name
    target_word =  Word.find_by(name: target).name

    # FIXME this is a Cypher injection risk
    path_source_to_target = Neo4j::Session.query("MATCH p=SHORTESTPATH((a{name:'#{source_word}'})--(b{name:'#{target_word}'})) RETURN extract(n IN nodes(p)| n.name) AS extracted")
    # what is the type of the object returned above
    # how to get it down to array of word names?
    return path_source_to_target.to_a
  end

  def self.random_pair(length)
    random_path = []

    while( random_path.none? ) do
      source_word = Neo4j::Session.query("MATCH (n) WITH n, rand() AS r WHERE length(n.name) = #{length} RETURN n.name AS word ORDER BY r LIMIT 1").first['word']
      target_word = Neo4j::Session.query("MATCH (n) WITH n, rand() AS r WHERE length(n.name) = #{length} RETURN n.name AS word ORDER BY r LIMIT 1").first['word']

      random_path = Neo4j::Session.query("MATCH p=SHORTESTPATH((a{name:'#{source_word}'})--(b{name:'#{target_word}'})) RETURN extract(n IN nodes(p)| n.name) AS extracted")
    end

    return random_path.to_a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_path
    @path = Word.find_path(params[:source], params[:target])

    respond_to do |format|
      format.html { @path }
      format.json { render json: @path.to_json, status: :ok }
    end
  end

  def get_random_path
    @path = Word.random_pair(params[:length])

    respond_to do |format|
      format.html { @path }
      format.json { render json: @path.to_json, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find_by_neo_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      # params.require(:word).permit(:name)
      params.permit(:name, :word, :target, :length)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Final</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/get_path.html.erb
<%= @path %>

app/views/words/get_random_path.html.erb
<%= @path %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.name %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @word.name %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>